# Generated by Django 4.1.4 on 2022-12-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
    ]
